<script type="text/javascript">
	var statusnet_template = '<div class="friend"><img src="{{profile_image}}" /> {{name}} (<a href="http://identi.ca/{{screen_name}}" target="_new">@{{screen_name}}</a>)</div>';
	var twitter_template = '<div class="friend"><img src="{{profile_image}}" /> {{name}} (<a href="http://twitter/{{screen_name}}" target="_new">@{{screen_name}}</a>)</div>';
	
	$(document).ready(function() {
		$('#button_search').click(function() {

			$('#loader').fadeIn();
			$('#username_results').hide();
			$('#friends_results').hide();
			$('#error').hide();
			
			$('#username_available').html('');
			$('#statusnet_count').html('');
			$('#twitter_count').html('');
			$('#statusnet_friends').html('');
			$('#twitter_friends').html('');
			
			// Do a username search
			$.ajax({
				data: { username: $('#twitter_username').val() },
				dataType: 'json',
				success: function(data, status, rq) {
					var message = '';
					if(data.exists) {
						message = 'Sorry, this username already exists.';
					} else {
						message = 'Great, this username is still available!';
					}
					
					$('#username_available').html(message);
				},
				type: 'POST',
				url: '<?php echo $this->baseURL(); ?>/worker/username'
			});
			
			// Do a friends lookup
			$.ajax({
				data: { username: $('#twitter_username').val() },
				dataType: 'json',
				success: function(data, status, rq) {
					if(data != null) {
						$('#statusnet_count').html(data.statusnet.length);
						$('#twitter_count').html(data.twitter.length);

						for(var i in data.statusnet) {
							var html = Mustache.to_html(statusnet_template, data.statusnet[i]);
							$('#statusnet_friends').append(html);
						}

						for(var i in data.twitter) {
							var html = Mustache.to_html(twitter_template, data.twitter[i]);
							$('#twitter_friends').append(html);

						}

						$('#loader').hide();
						$('#username_results').fadeIn();					
						$('#friends_results').fadeIn();						
					} else {
						$('#loader').hide();
						$('#error').fadeIn();
					}
				},
				type: 'POST',
				url: '<?php echo $this->baseURL(); ?>/worker/twitterfriends'
			});
			
			return false;
		});
	});
</script>

<?php if(!isset($_SESSION['TWITTER_ACCESS_TOKEN'])): ?>
	<p>
		To begin, we will need to log into Twitter. We do this to help with Twitter's rate limit, and will not post anything to your account.
	</p>
	
	<p>
		<a href="<?php echo $this->baseUrl(); ?>/auth/"><img src="<?php echo $this->baseUrl(); ?>/images/sign-in-with-twitter-l.png"></a>
	</p>
<?php else: ?>
	<div id="search_area">
		<p>
			To get us started, please type in your Twitter username. Since we're just gathering public data, there is no need to log into Twitter. Click on "Let's Begin" and we will check to see if your username is available on Identi.ca, and then check your friends.
		</p>

		<p>
			If you have any ideas on improving this service (and I have a few of my own), head on over to our <a href="https://github.com/dragonmantank/FlyAway" target="_new">github page</a> and log an <a href="https://github.com/dragonmantank/FlyAway/issues" target="_new">Issue</a>. 
		</p>

		<form>
			Twitter Username: <input type="text" id="twitter_username" /> <input type="submit" id="button_search" value="Let's Begin" />
		</form>
	</div>

	<div id="loader">
		<div id="loader_message">Compiling all the information. The more friends you have, the longer this will take...</div>
		<img src="<?php echo $this->baseUrl(); ?>/css/images/ajax-loader.gif" />
	</div>

	<div id="error">
		<p>
			Oops, we couldn't find that Twitter username. Maybe it was misspelled?
		</p>
	</div>

	<div id="username_results">
		<h3>Is your username available?</h3>

		<p id="username_available"></p>
	</div>

	<div id="friends_results">
		<h3>What about your friends?</h3>

		<p>
			Friends who have (possibly) switched: <span id="statusnet_count"></span>
		</p>

		<p>
			Friends who have (possibly) not switched: <span id="twitter_count"></span>
		</p>

		<div>
			<h4>Friends on StatusNet</h4>
			<div id="statusnet_friends"></div>
		</div>

		<div>
			<h4>Friends only on Twitter</h4>
			<div id="twitter_friends"></div>
		</div>
	</div>
<?php endif; ?>