<script type="text/javascript">
	var statusnet_template = '<div class="friend" id="friend_{{screen_name}}"><img src="{{profile_image}}"/></div>';
	var twitter_template = '<div class="friend" id="friend_{{screen_name}}"><img src="{{profile_image}}"/></div>';
	
	function subscribe(screen_name, name) {
		if(<?php echo $this->allowSubscribe; ?>) {
			$.ajax({
				data: { 'screen_name': screen_name },
				dataType: 'json',
				success: function(data, status, rq) {
					var message = '';
					if(data.status) {
						message = 'Great, you\'ve subscribed to '+screen_name;
					} else {
						message = 'Oops, we couldn\'t follow that user';
					}

					alert(message);
					var id = '#friend_'+screen_name;
					$(id).hide().appendTo('#statusnet_existing_friends');
					$(id).poshytip({
						className: 'tip-yellow',
						content: '<a href="http://identi.ca/'+screen_name+'" target="_new">View '+name+'\'s Profile</a>',
						allowTipHover: true
					});
					$(id).fadeIn()
				},
				type: 'POST',
				url: '<?php echo $this->baseUrl(); ?>/worker/identicafollow'
			});
		} else {
			alert('Please sign into Identi.ca to follow uses through FlyAway.');
			return false;
		}
	}
	
	$(document).ready(function() {
		$('#button_search').click(function() {

			$('#loader').fadeIn();
			$('#username_results').hide();
			$('#friends_results').hide();
			$('#error').hide();
			
			$('#username_available').html('');
			$('#statusnet_count').html('');
			$('#twitter_count').html('');
			$('#statusnet_friends').html('');
			$('#twitter_friends').html('');
			
			// Do a username search
			$.ajax({
				data: { username: $('#twitter_username').val() },
				dataType: 'json',
				success: function(data, status, rq) {
					var message = '';
					if(data.exists) {
						message = 'Sorry, this username already exists.';
					} else {
						message = 'Great, this username is still available!';
					}
					
					$('#username_available').html(message);
				},
				type: 'POST',
				url: '<?php echo $this->baseUrl(); ?>/worker/username'
			});
			
			// Do a friends lookup
			$.ajax({
				data: { username: $('#twitter_username').val() },
				dataType: 'json',
				success: function(data, status, rq) {
					if(data != null) {
						if(data.statusnet_subscribed != undefined || data.statusnet_subscribed != '') {
							for(var i in data.statusnet_subscribed) {
								var friend = data.statusnet_subscribed[i];
								var html = Mustache.to_html(statusnet_template, friend);
								$('#statusnet_existing_friends').append(html);
								$('#friend_'+friend.screen_name).poshytip({
									className: 'tip-yellow',
									content: '<a href="http://identi.ca/'+friend.screen_name+'" target="_new">View '+friend.name+'\'s Profile</a>',
									allowTipHover: true
								});
								$('#statusnet_existing_friends_container').show();
							}
						}

						for(var i in data.statusnet) {
							var friend = data.statusnet[i];
							var html = Mustache.to_html(statusnet_template, data.statusnet[i]);
							$('#statusnet_friends').append(html);
							$('#friend_'+friend.screen_name).poshytip({
								className: 'tip-yellow',
								content: '<a href="javascript:void(0);" onClick="subscribe(\''+friend.screen_name+'\', \''+friend.name+'\');">Subscribe to '+friend.name+' on Identi.ca</a><br /><a href="http://identi.ca/'+friend.screen_name+'" target="_new">View '+friend.name+'\'s Profile</a>',
								allowTipHover: true
							});
						}

						for(var i in data.twitter) {
							var friend = data.twitter[i];
							var html = Mustache.to_html(twitter_template, data.twitter[i]);
							$('#twitter_friends').append(html);
							$('#friend_'+friend.screen_name).poshytip({
								className: 'tip-yellow',
								content: '<a href="http://www.twitter.com/'+friend.screen_name+'" target="_new">View '+friend.name+'\'s Twitter Profile</a>',
								allowTipHover: true
							});
						}
						
						$('#loader').hide();
						$('#username_results').fadeIn();					
						$('#friends_results').fadeIn();						
					} else {
						$('#loader').hide();
						$('#error').fadeIn();
					}
				},
				type: 'POST',
				url: '<?php echo $this->baseURL(); ?>/worker/twitterfriends'
			});
			
			return false;
		});
	});
</script>

<?php if(!isset($_SESSION['IDENTICA_ACCESS_TOKEN'])): ?>
	<p>
		If you have an Identi.ca account, click the button to sign in below. We'll use this information to narrow down who you aren't following on Identi.ca that you aren't on Twitter. This is not required, but it will make the results more usable, and let you subscribe to people from FlyAway!
	</p>
	
	<p>
		<a href="<?php echo $this->baseUrl(); ?>/auth/identica"><img src="<?php echo $this->baseUrl(); ?>/images/sign-in-with-identica-l.png"></a>
	</p>
<?php else: ?>
	<p>
		Great, we're signed into Identi.ca!
	</p>
<?php endif; ?>

<?php if(!isset($_SESSION['TWITTER_ACCESS_TOKEN'])): ?>
	<p>
		To begin, we will need to log into Twitter. We do this to help with Twitter's rate limit, and will not post anything to your account.
	</p>
	
	<p>
		<a href="<?php echo $this->baseUrl(); ?>/auth/"><img src="<?php echo $this->baseUrl(); ?>/images/sign-in-with-twitter-l.png"></a>
	</p>
<?php else: ?>
	<div id="search_area">
		<p>
			Welcome <?php echo $this->access_token->screen_name; ?>!
		<p>
			To get started, just click on "Let's Begin". We'll connect to your Twitter account and grab your friends list. With the list, we'll compare that to Identi.ca's users and see if any of the usernames match. Since we cache some of this data, if some of your friends have switched over within the last hour, FlyAway may not have noticed yet.
		</p>

		<p>
			If you have any ideas on improving this service (and I have a few of my own), head on over to our <a href="https://github.com/dragonmantank/FlyAway" target="_new">github page</a> and log an <a href="https://github.com/dragonmantank/FlyAway/issues" target="_new">Issue</a>. 
		</p>

		<form>
			<input type="submit" id="button_search" value="Let's Begin" />
		</form>
	</div>

	<div id="loader">
		<div id="loader_message">Compiling all the information. The more friends you have, the longer this will take...</div>
		<img src="<?php echo $this->baseUrl(); ?>/css/images/ajax-loader.gif" />
	</div>

	<div id="error">
		<p>
			Oops, we couldn't find that Twitter username. Maybe it was misspelled?
		</p>
	</div>

	<div id="username_results">
		<h3>Is your username available?</h3>

		<p id="username_available"></p>
	</div>

	<div id="friends_results">
		<h3>What about your friends?</h3>

		<div style="display: none; clear: both" id="statusnet_existing_friends_container">
			<h4>Friends on StatusNet You Already Follow</h4>
			<div id="statusnet_existing_friends"></div>
		</div>

		<div style="clear: both">
			<h4>Friends on StatusNet You Need to Follow</h4>
			<div id="statusnet_friends"></div>
		</div>

		<div style="clear: both">
			<h4>Friends only on Twitter</h4>
			<div id="twitter_friends"></div>
		</div>
	</div>
<?php endif; ?>
